#!/usr/bin/env bash
# Part 4 §12 — 20 flips. Run from /workspace/stable-audio-3. Set LORA and IN first:
#   export LORA=/workspace/sweeps/run_r16a16_lr2e4/<best>.safetensors IN=/workspace/mybeat.wav
set -u
mkdir -p /workspace/flips
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, trap, dark, 808 heavy, sub bass, gritty, distorted, energetic" --strength 0.5  --duration 30 --out /workspace/flips/trapdark.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, boom bap, dusty vinyl, warm, soulful, gritty, melodic" --strength 0.55 --duration 30 --out /workspace/flips/boombap.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, lofi, tape saturated, dusty vinyl, warm, nostalgic, mellow, laid back" --strength 0.5  --duration 30 --out /workspace/flips/lofi.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, drill, dark, hypnotic, sliding 808, sub bass, distorted" --strength 0.6  --duration 30 --out /workspace/flips/drill.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.65 --input "$IN" --prompt "hip hop, loop, cinematic, epic, dark, string section, 808 heavy, sub bass, dramatic" --strength 0.6  --duration 30 --out /workspace/flips/cinematic.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, boom bap, soulful, warm, gospel organ, dusty vinyl, uplifting, melodic" --strength 0.55 --duration 30 --out /workspace/flips/soulful.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, west coast, g-funk, funky, warm, synth lead, bass heavy, melodic" --strength 0.6  --duration 30 --out /workspace/flips/westcoast.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.65 --input "$IN" --prompt "hip hop, loop, mellow, dreamy, ethereal, spacey, reverb drenched, warm, lush, melodic" --strength 0.55 --duration 30 --out /workspace/flips/dreamy.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, boom bap, raw, gritty, distorted, dark, dusty vinyl, drum heavy" --strength 0.5  --duration 30 --out /workspace/flips/gritty.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, trap, 2020s, clean, modern, 808 heavy, sub bass, energetic, hypnotic" --strength 0.55 --duration 30 --out /workspace/flips/2020s.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, trap, eerie, ominous, dark, tense, 808 heavy, sub bass, distorted" --strength 0.6  --duration 30 --out /workspace/flips/eerie.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, boom bap, jazzy, rhodes, upright bass, soulful, warm, dusty vinyl, mellow" --strength 0.55 --duration 30 --out /workspace/flips/jazzy.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, trap, hard hitting, aggressive, dark, 808 heavy, sub bass, distorted, energetic" --strength 0.5  --duration 30 --out /workspace/flips/hard.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, mellow, warm, soulful, dusty vinyl, laid back, melodic, nostalgic" --strength 0.5  --duration 30 --out /workspace/flips/warm.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, minimal, sparse, dark, hypnotic, sub bass, 808 heavy, mellow" --strength 0.55 --duration 30 --out /workspace/flips/minimal.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, trap, phonk, memphis, distorted, dark, 808 heavy, sub bass, gritty" --strength 0.65 --duration 30 --out /workspace/flips/phonk.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, boom bap, uplifting, bright, soulful, warm, brass stabs, melodic" --strength 0.55 --duration 30 --out /workspace/flips/uplift.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, trap, dark, 808 heavy, sub bass, distorted, hard hitting, energetic" --strength 0.85 --duration 30 --out /workspace/flips/heavyremix.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, warm, dusty vinyl, gritty, melodic, soulful" --strength 0.3  --duration 30 --out /workspace/flips/lighttouch.wav
.venv/bin/python scripts/sa3_workflow.py flip --model medium-base --lora "$LORA" --lora-strength 0.7  --input "$IN" --prompt "hip hop, loop, boom bap, swung drums, dusty vinyl, hard hitting, gritty, warm, melodic" --strength 0.5  --duration 30 --out /workspace/flips/drumswap.wav
